### ISSUE TITLE
insight on how to compile this?

### ISSUE THREAD

**Issue by wildeyevr** [vjacob/ofxHPVPlayer#10]
just curious if someone could provide a brief explanation of how to use this standalone without unity... thanks...

**Comment by wildeyevr** [comment]
sorry just realized it's an openFrameworks addon... nevermind...

**Comment by vjacob** [comment]
Hello @wildeyevr , you can easily use this in any C or C++ program, without Unity or OpenFrameworks. 

The ofxHPVPlayer.h and ofxHPVPlayer.cpp files are just OF style wrappers around the underlying code. I suggest you took a look at those and start from there.
