### ISSUE TITLE
How to encode HPV from command-line?

### ISSUE THREAD

**Issue by anselanza** [vjacob/ofxHPVPlayer#2]
Hi, and thanks for the amazing addon. Already having superb results!

I know you recommend the Holo Toolset "HPV Creator" app to encode the videos, but are there any ways to do this from a command line tool? I need this in order to automate some of my encoding, so I don't have to go through a GUI tool. I see that ffmpeg in theory supports HAP encoding (https://gist.github.com/dlublin/e4585b872dd136ae88b2aa51a6a89aac) but this is used to produce `.mov` files which don't appear to meet the requirements of the HPVPlayer.

**Comment by vjacob** [comment]
Hi @anselanza, I've made a command-line tool to create HPV files. You find it at: https://github.com/HasseltVR/Holo_Toolset/tree/master/HPV_Creator_Console.

Best
