### ISSUE TITLE
macOS and OF 0.10.0 ?

### ISSUE THREAD

**Issue by stephanschulz** [vjacob/ofxHPVPlayer#3]
Hey
I would love to test you HAP add-on. I used ofxHAPAVPlayer in past project but it's not been updated for OF 0.10.
Out of the box yours unfortunately also does not compile successfully.
Any tips on what to do or because of the missing quicktime it will not work?
thx

**Comment by vjacob** [comment]
Hi Stephan, 

I haven't checked the addon on OF 0.10, will try to do so this weekend. What platform are you on?

By the way, my addon doesn't play HAP files. It's built around it's own video format, called HPV, despite using comparable technologies under the hood.

Best

**Comment by stephanschulz** [comment]
I am on macOS 10.12.6.
It would be so great if you have time to make it work for the newest OF release. 
Do you think the missing quicktime might become an issue too or since you are using your own video format it might work?

**Comment by vjacob** [comment]
This add-on is completely independent from Quicktime, or any other platform-specific framework for that matter.

**Comment by vjacob** [comment]
Hi @stephanschulz , 

I've committed some small fixes for the examples to run on OF 0.10. The HPV library itself just compiled without issue.  I tried both the release version and the master branch from Git.

Does this solve your issue, or are you experiencing something else?

Best,
Vincent

**Comment by antimodular** [comment]
Thanks it works very well. 
Great addon :)
Having to export my videos to photos and then reassemble them via HPVcreator is a bit of extra work. But hey :)
