### ISSUE TITLE
PRId64

### ISSUE THREAD

**Issue by ceathar** [vjacob/ofxHPVPlayer#4]
Hello,

I had a problem with compiling under windows10 / msys2, with the following error :

`error: expected ')' before 'PRId64'`

(on lines 309, 331, 345, at HPV_ERROR definitions)

To resolve it, I had to add these two lines first

```
#define __STDC_FORMAT_MACROS
#include <inttypes.h>
```

I have never used PRId64 before, so I'll let you tell me if it is relevant.
thanks,

**Comment by vjacob** [comment]
Hi @ceathar , 

The PRId64 macro makes sure 64bit integer types are printed correctly in a cross-platform way (not all systems are 64bit). So it should indeed stay in place. 
I haven't tested on msys2 environment so thanks for posting this fix. However, is the first line (#define __STDC_FORMAT_MACROS) really necessary? I would expect that #include <inttypes.h> would be sufficient.

Anyway, I would appreciate it when you could me a pull request so I can include your fix in the master branch.

Best,

**Comment by vjacob** [comment]
Closed, solved through #5
