### ISSUE TITLE
loading many files

### ISSUE THREAD

**Issue by antimodular** [vjacob/ofxHPVPlayer#6]
Working of the example-sync-multiple-videos i expanded to load a vector of many videos.
But it seems more than 7 videos can't be loaded? Is that due to my GPU limit?
I have 16 GB ram, Radeon Pro 460 4096 MB and Intel HD Graphics 530 1536 MB on macOS 10.12.

Each video is 640x480, about 100 MB per video.

<img width="1137" alt="screen shot 2018-11-05 at 7 56 11 pm" src="https://user-images.githubusercontent.com/3649364/48036187-38f69300-e135-11e8-8ff3-dfa7daf61b0c.png">

here one of my files
https://www.dropbox.com/s/jm4anc41np959rz/File1.hpv?dl=0

Here is my test code
https://gist.github.com/antimodular/0ab4cde706da4f0b440fae37bf2631eb

Thanks for any advice.

**Comment by antimodular** [comment]
oh i see MAX_NUMBER_OF_PLAYERS was set to 6 inside HPVManager.h

but i also learned that 60 640x480 videos are too much to play at the same time.
do you have any advice on how to get many (360) video files playing?

**Comment by vjacob** [comment]
Hello, 
This kind of usage would require a different implementation, where each player holds some pointers to pre-buffered frames (on RAM or GPU) and some playback state but where the actual reading from disk is delegated to a threaded player manager instance. 
Although such improvements were planned initially, I can't invest that time in it for the moment. 

If all your videofiles have the same length (or are at least some of them), you could 'tile' small videoclips in one big file. For example an 6400x4800 videofile would hold already 100x 640x480 videofiles. By using a draw subsection method you can then draw the part of the texture you need at a desired location. Such a 6400x4800 file shouldn't pose an issue on a modern machine.

Now that I come to think of it, I haven't provided such a draw subsection method. Will do asap.

**Comment by antimodular** [comment]
Thanks again for your advice.
Yes the draw subsection would be very good to have. If you do have time i would love to test it soon.

**Comment by vjacob** [comment]
Hello, 

I added a drawSubsection method in commit https://github.com/vjacob/ofxHPVPlayer/commit/351eb3b8dd805b42b41cb1f8aaaef9ba2b9ccfdd

Will consider issue closed.
