### ISSUE TITLE
Using example-slave-to-audio play hpv not smooth

### ISSUE THREAD

**Issue by fingerx** [vjacob/ofxHPVPlayer#7]
Hello,Using of 0.10.0 build example-slave-to-audio  success but play hpv file is not smooth and can feel the jitter of the video.

My hpv file is 4096X4096,dx1,62.7GB, wav file 68M,32000hz,2 channel
Test two pc: a. dell t7910, xeon cpu e5-2630v4@2.2Ghz, amd firepro w8100,toshiba scsi disk device
                    b.dell t5820, xeon cpu w2145@3.7Ghz,nv p4000,intel 900p ssd

I am wondering if this synchronization method is flawed. The sound can be played smoothly, but the synchronization of the video is the seek to pos method. This takes time, so it will cause this. Is there any way to improve it? thank you very much.

**Comment by vjacob** [comment]
Hi @fingerx , 

Did you call **hpvPlayer.setPaused(true)** when loading your file? Please also make sure to compile in Release mode. I've seen some issues with stuttering playback when I compile in Debug mode.

**Comment by fingerx** [comment]
@vjacob  thanks, using your github example and build in release mode.And I also tried the hpv unity3d version, which has the same problem. If you need me to provide a test sample, please let me know. The file is very large and I will present 2 minutes of video and audio. Thanks again.

**Comment by vjacob** [comment]
I'll take a look. A test sample (a couple of seconds is enough) of your video would be helpful indeed.

**Comment by fingerx** [comment]
@vjacob Sorry, I spent some time uploading files.[https://mega.nz/#F!sE0EGAgb!Gus2IRyr4Os21IuAT-wu0g](url)

**Comment by fingerx** [comment]
@vjacob need your help,thanks

**Comment by vjacob** [comment]
Hi, will look into it tonight.

**Comment by fingerx** [comment]
@vjacob  thanks very much.

**Comment by vjacob** [comment]
Hi @fingerx , please pull my latest commit https://github.com/vjacob/ofxHPVPlayer/commit/6e824aa047fc952821eaf9c2a17242b6402cbf50 

This fixes a bug where seeking to the same frame used up resources. It also enable to en/disable synchronous seeking. 
Please also try to en double-buffering through hpvPlayer.setDoubleBuffered(true). I've tested with your video and get much better results using the above commit and with double buffering set to true.

**Comment by fingerx** [comment]
@vjacob thanks very much.
