### ISSUE TITLE
Sync over network

### ISSUE THREAD

**Issue by Vamoss** [vjacob/ofxHPVPlayer#8]
Hi @vjacob !

Do you have good experience in frame syncing videos over network with ofxHPVPlayer?

We noticed that over time, the frame between computers are losing sync.
We also tried sending the current frame over network, but the varying network latency does not help.

Cheers!
Carlos

**Comment by vjacob** [comment]
Hi @Vamoss , 

I'm not surprised that playing videofiles on different machines doesn't stay in sync. With any videoplayer, not only with my addon for that matter, you would need some means of external sync. 

I haven't tried any setup like yours with different machines. Some things I can think of:

1. If your files are relatively short, use one master machine that controls the transport (start, stop, ...). When a slave is done, it will wait until it receives a new transport trigger from the master. This way starting a new video is synchronised over the different machines.

2. If your files are longer you can maybe try to only send a sync message from one master with the current frame it's playing each 5/10/... seconds to all slaves. Each slave is started in normal play mode, but upon receiving a sync message will seek to that frame. It is my experience that this is somewhat a self-regulating system. In the beginning, slaves may stutter a bit upon seeking but this is smoothed out on later syncs.

Try to use short UDP messages, preferably Broadcast or even Multicast, to keep the overhead low. You can measure the time it takes for one message to travel from one master to a slave and compensate for that in the frame number used for seeking in a slave.

Hope this helps.

**Comment by vjacob** [comment]
Closed as issue is not specifically related to this addon.
