### ISSUE TITLE
Can not use multiple GPU in a single OF application

### ISSUE THREAD

**Issue by DeqingSun** [vjacob/ofxHPVPlayer#9]
Hi, This addon really plays video efficiently, nice work.

However, the current singleton structure seems to make it impossible to use multiple renderers. If I try to use ofxHPVPlayer in multiple GPU setup, it uses a single GPU to decode and make the display really slow.

Is there any way to create multiple instances of ofxHPVPlayer that ties to different windows in a single OF application? Thanks.

**Comment by vjacob** [comment]
Hello, 

This would only be possible using vendor specific extensions, like those for [NVidia](https://www.khronos.org/registry/OpenGL/extensions/NV/WGL_NV_gpu_affinity.txt) or [AMD](https://www.khronos.org/registry/OpenGL/extensions/AMD/WGL_AMD_gpu_association.txt) cards. 

Sadly I don't have the time to invest in supporting those. 

Apologies, Vincent
